#version 430

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba8, binding = 0) uniform image2D outputImage;

struct Sphere 
{
    vec4 positionr;  // (x, y, z, r)
};

layout(std430, binding = 1) buffer SphereBuffer 
{
    Sphere spheres[];
};

// layout(std430, binding = 2) buffer DepthBuffer 
// {
//     float depthData[];
// };

layout(std430, binding = 3) buffer CounterBuffer {
    uint counter;
};

struct SphereBillboard 
{
    vec4 cameraSpaceSphPosR;    // 16b - camera space position of the sphere and radius
    vec4 upRightCornerMaxX;     // 16b - up right corner of the billboard in camera space and the max X coordinate in screen space 
    vec4 upLeftCornerMaxY;      // 16b - up left corner of the billboard in camera space and the max Y coordinate in screen space
    vec4 downRightCornerMinX;   // 16b - down right corner of the billboard in camera space and the min X coordinate in screen space
    vec4 downLeftCornerMinY;    // 16b - down left corner of the billboard in camera space and the min Y coordinate in screen space
    // 64b
}; 

layout(std430, binding = 2) buffer SphereBillboardDataBuffer
{
    SphereBillboard sphereBillboardData[];
};

uniform mat4 view;
uniform mat4 proj;

uniform vec4 frustumTopFace;
uniform vec4 frustumBottomFace;
uniform vec4 frustumRightFace;
uniform vec4 frustumLeftFace;
uniform vec4 frustumFarFace;
uniform vec4 frustumNearFace;

uniform vec3 front;
uniform vec3 up;
// uniform vec3 right;
uniform vec3 cameraPos;

uniform ivec2 screenResolution;

uniform int sphereCount;

vec3 lightColor = vec3(0.01, 1.0, 0.05);
float diffuseI = 0.9;

struct bboxCorners
{
    // view space
    vec3 upRightCorner;
    vec3 upLeftCorner;
    vec3 downRightCorner;
    vec3 downLeftCorner;

    // screen space
    vec2 minCorner;
    vec2 maxCorner;
    
};

// frustum culling

bool isOnOrForwardOfPlane(vec4 plane, vec4 sphere)
{
    return dot(vec3(plane), vec3(sphere)) - plane.w >= -sphere.w;
}

bool isSphereInside(Sphere sph)
{
    return isOnOrForwardOfPlane(frustumLeftFace, sph.positionr) &&
           isOnOrForwardOfPlane(frustumRightFace, sph.positionr) &&
           isOnOrForwardOfPlane(frustumFarFace, sph.positionr) &&
           isOnOrForwardOfPlane(frustumNearFace, sph.positionr) &&
           isOnOrForwardOfPlane(frustumTopFace, sph.positionr) &&
           isOnOrForwardOfPlane(frustumBottomFace, sph.positionr);
}

// frustum culling



bboxCorners getSphereBbox(const vec3 cameraSpaceSphere, const vec3 camImposPos, 
    const vec3 normCamSpaceSphere, const float sphRadius)
{
    const float sinAngle = sphRadius / (length(cameraSpaceSphere) + 1e-6f);
    const float tanAngle = tan(asin(sinAngle));
    const float quadScale = tanAngle * length(camImposPos);

    vec3 impU = normalize(cross(normCamSpaceSphere, up));
    vec3 impV = cross(impU, normCamSpaceSphere) * quadScale;
    impU *= quadScale;

    const vec3 upRightCorner = camImposPos + impU + impV;
    const vec3 upLeftCorner = camImposPos - impU + impV;
    const vec3 downRightCorner = camImposPos + impU - impV;
    const vec3 downLeftCorner = camImposPos - impU - impV;

    const vec4 upRight = proj * vec4(upRightCorner, 1.0f);
    const vec4 upLeft = proj * vec4(upLeftCorner, 1.0f);
    const vec4 downRight = proj * vec4(downRightCorner, 1.0f);
    const vec4 downLeft = proj * vec4(downLeftCorner, 1.0f);
    
    const vec3 ndcUpRight = vec3(upRight.x / upRight.w, upRight.y / upRight.w, upRight.z / upRight.w);
    const vec3 ndcUpLeft = vec3(upLeft.x / upLeft.w, upLeft.y / upLeft.w, upLeft.z / upLeft.w);
    const vec3 ndcDownRight = vec3(downRight.x / downRight.w, downRight.y / downRight.w, downRight.z / downRight.w);
    const vec3 ndcDownLeft = vec3(downLeft.x / downLeft.w, downLeft.y / downLeft.w, downLeft.z / downLeft.w);

    vec2 minCorner = min(min(ndcUpRight.xy, ndcUpLeft.xy), min(ndcDownRight.xy, ndcDownLeft.xy));
    vec2 maxCorner = max(max(ndcUpRight.xy, ndcUpLeft.xy), max(ndcDownRight.xy, ndcDownLeft.xy));


    return bboxCorners(upRightCorner, upLeftCorner, downRightCorner, downLeftCorner, minCorner, maxCorner); 
}

void storeSphereBBox(Sphere sphere)
{
    vec3 cameraSpaceSphere = vec3(view * vec4(sphere.positionr.xyz, 1.0f));
    vec3 normCamSpaceSphere = normalize(cameraSpaceSphere);
    vec3 camImposPos = cameraSpaceSphere - normCamSpaceSphere * sphere.positionr.w;

    bboxCorners sphereBbox = getSphereBbox(cameraSpaceSphere, camImposPos,
        normCamSpaceSphere, sphere.positionr.w);
    
    ivec2 screenMin, screenMax;

    screenMin.x = int(((sphereBbox.minCorner.x) * 0.5f + 0.5f) * float(screenResolution.x));
    screenMin.y = int((sphereBbox.minCorner.y * 0.5f + 0.5f) * float(screenResolution.y));
    screenMax.x = int(((sphereBbox.maxCorner.x) * 0.5f + 0.5f) * float(screenResolution.x));
    screenMax.y = int((sphereBbox.maxCorner.y * 0.5f + 0.5f) * float(screenResolution.y));

    uint currentCounter = atomicAdd(counter, 1);
    sphereBillboardData[int(currentCounter)] =
        SphereBillboard(vec4(cameraSpaceSphere, sphere.positionr.w), 
            vec4(sphereBbox.upRightCorner, screenMax.x), 
            vec4(sphereBbox.upLeftCorner, screenMax.y), 
            vec4(sphereBbox.downRightCorner, screenMin.x), 
            vec4(sphereBbox.downLeftCorner, screenMin.y));
    
}


void main() 
{
    uint index = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_WorkGroupSize.x;

    // Check if the index is out of bounds
    if (index >= sphereCount) {
        return;  // If index is greater that the amount of spheres, return
    }

    // Get sphere bbox
    Sphere s = spheres[index];
    if (isSphereInside(s))
        storeSphereBBox(s);
}