#version 430

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba8, binding = 0) uniform image2D outputImage;

struct Sphere 
{
    vec4 positionr;  // (x, y, z, r)
};

layout(std430, binding = 1) buffer SphereBuffer 
{
    Sphere spheres[];
};

// layout(std430, binding = 2) buffer DepthBuffer 
// {
//     float depthData[];
// };

struct SphereBillboard 
{
    vec4 cameraSpaceSphPosR;    // 16b - camera space position of the sphere and radius
    vec4 upRightCornerMaxX;     // 16b - up right corner of the billboard in camera space and the max X coordinate in screen space 
    vec4 upLeftCornerMaxY;      // 16b - up left corner of the billboard in camera space and the max Y coordinate in screen space
    vec4 downRightCornerMinX;   // 16b - down right corner of the billboard in camera space and the min X coordinate in screen space
    vec4 downLeftCornerMinY;    // 16b - down left corner of the billboard in camera space and the min Y coordinate in screen space
    // 64b
}; 

layout(std430, binding = 2) buffer SphereBillboardDataBuffer
{
    SphereBillboard sphereBillboardData[];
};

uniform mat4 view;
uniform mat4 proj;

uniform vec3 front;
uniform vec3 up;
// uniform vec3 right;
uniform vec3 cameraPos;

uniform ivec2 screenResolution;

uniform float fov;
uniform float aspectRatio;
uniform int sphereCount;

vec3 lightColor = vec3(0.01, 1.0, 0.05);
float diffuseI = 0.9;

struct bboxCorners
{
    // view space
    vec3 upRightCorner;
    vec3 upLeftCorner;
    vec3 downRightCorner;
    vec3 downLeftCorner;

    // screen space
    vec2 minCorner;
    vec2 maxCorner;
    
};

// uint vecToColor(vec3 lambertCos) {
//     uint R = uint(lambertCos.r * 255.0);
//     uint G = uint(lambertCos.g * 255.0);
//     uint B = uint(lambertCos.b * 255.0);
//     return (R << 0) | (G << 8) | (B << 16) | (0xFF << 24);
// }



bboxCorners getSphereBbox(const vec3 cameraSpaceSphere, const vec3 camImposPos, 
    const vec3 normCamSpaceSphere, const float sphRadius)
{
    const float sinAngle = sphRadius / (length(cameraSpaceSphere) + 1e-6f);
    const float tanAngle = tan(asin(sinAngle));
    const float quadScale = tanAngle * length(camImposPos);

    vec3 impU = normalize(cross(normCamSpaceSphere, up));
    vec3 impV = cross(impU, normCamSpaceSphere) * quadScale;
    impU *= quadScale;

    const vec3 upRightCorner = camImposPos + impU + impV;
    const vec3 upLeftCorner = camImposPos - impU + impV;
    const vec3 downRightCorner = camImposPos + impU - impV;
    const vec3 downLeftCorner = camImposPos - impU - impV;

    const vec4 upRight = proj * vec4(upRightCorner, 1.0f);
    const vec4 upLeft = proj * vec4(upLeftCorner, 1.0f);
    const vec4 downRight = proj * vec4(downRightCorner, 1.0f);
    const vec4 downLeft = proj * vec4(downLeftCorner, 1.0f);
    
    const vec3 ndcUpRight = vec3(upRightCorner) / upRight.w;
    const vec3 ndcUpLeft = vec3(upLeftCorner) / upLeft.w;
    const vec3 ndcDownRight = vec3(downRightCorner) / downRight.w;
    const vec3 ndcDownLeft = vec3(downLeftCorner) / downLeft.w;

    vec2 minCorner = min(min(ndcUpRight.xy, ndcUpLeft.xy), min(ndcDownRight.xy, ndcDownLeft.xy));
    vec2 maxCorner = max(max(ndcUpRight.xy, ndcUpLeft.xy), max(ndcDownRight.xy, ndcDownLeft.xy));


    return bboxCorners(upRightCorner, upLeftCorner, downRightCorner, downLeftCorner, minCorner, maxCorner); 
}

void storeSphereBBox(Sphere sphere)
{
    vec3 cameraSpaceSphere = vec3(view * vec4(sphere.positionr.xyz, 1.0f));
    vec3 normCamSpaceSphere = normalize(cameraSpaceSphere);
    vec3 camImposPos = cameraSpaceSphere - normCamSpaceSphere * sphere.positionr.w;

    bboxCorners sphereBbox = getSphereBbox(cameraSpaceSphere, camImposPos,
        normCamSpaceSphere, sphere.positionr.w);
    
    ivec2 screenMin, screenMax;

    screenMin.x = int(((sphereBbox.minCorner.x/aspectRatio) * 0.5f + 0.5f) * float(screenResolution.x));
    screenMin.y = int((sphereBbox.minCorner.y * 0.5f + 0.5f) * float(screenResolution.y));
    screenMax.x = int(((sphereBbox.maxCorner.x/aspectRatio) * 0.5f + 0.5f) * float(screenResolution.x));
    screenMax.y = int((sphereBbox.maxCorner.y * 0.5f + 0.5f) * float(screenResolution.y));

    if (dot(sphere.positionr.xyz - cameraPos, front) > 0.5f && 
        !((screenMin.x < 0 && screenMax.x > screenResolution.x) || 
        (screenMin.y < 0 && screenMax.y > screenResolution.y)) &&
        !((screenMin.x > screenResolution.x || screenMax.x < 0) || 
        (screenMin.y > screenResolution.y || screenMax.y < 0))) 
    {
        sphereBillboardData[gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_WorkGroupSize.x] =
            SphereBillboard(vec4(cameraSpaceSphere, sphere.positionr.w), 
                vec4(sphereBbox.upRightCorner, screenMax.x), 
                vec4(sphereBbox.upLeftCorner, screenMax.y), 
                vec4(sphereBbox.downRightCorner, screenMin.x), 
                vec4(sphereBbox.downLeftCorner, screenMin.y));
    } else 
    {
        sphereBillboardData[gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_WorkGroupSize.x] =
            SphereBillboard(vec4(0.0), vec4(0.0), vec4(0.0), vec4(0.0), vec4(0.0));
    }
}


void main() 
{
    uint index = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_WorkGroupSize.x;

    // Check if the index is out of bounds
    if (index >= sphereCount) {
        return;  // If index is greater that the amount of spheres, return
    }

    // Get sphere bbox
    Sphere s = spheres[index];
    storeSphereBBox(s);
}