#version 430


layout(local_size_x = 16, local_size_y = 16) in;

struct SphereBillboard 
{
    vec4 cameraSpaceSphPosR;     // 16b - camera space position of the sphere and radius
    vec4 upRightCornerMaxX;     // 16b - up right corner of the billboard in camera space and the max X coordinate in screen space 
    vec4 upLeftCornerMaxY;      // 16b - up left corner of the billboard in camera space and the max Y coordinate in screen space
    vec4 downRightCornerMinX;   // 16b - down right corner of the billboard in camera space and the min X coordinate in screen space
    vec4 downLeftCornerMinY;    // 16b - down left corner of the billboard in camera space and the min Y coordinate in screen space
    // 80b
};

layout(std430, binding = 0) buffer SphereBillboardDataBuffer
{
    SphereBillboard sphereBillboardData[];
};

uniform int sphereCount;

uniform ivec2 screenResolution;

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    const int localID = int(gl_LocalInvocationIndex);
    const int threadsPerWorkGroup = int(gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z);
    const int batches = int((sphereCount-1) / threadsPerWorkGroup) + 1;
    const int lastBatchAmount = sphereCount - (batches-1) * threadsPerWorkGroup;
    int count = threadsPerWorkGroup;

    for (int batch = 0; batch < batches; batch++)
    {
        int batchIndex = localID + batch * threadsPerWorkGroup;
        if (batchIndex < sphereCount)
        {
            sphereBillboardData[batchIndex].cameraSpaceSphPosR.w = 
            -abs(sphereBillboardData[batchIndex].cameraSpaceSphPosR.w);
        }
        barrier();

    }    
}