#version 430


layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba8, binding = 0) uniform image2D outputImage;

layout(binding = 3, r32f) uniform image2D depthData;

layout(std430, binding = 6) buffer PixelOwnershipBuffer 
{
    uint pixelOwnershipBuffer[];
};

layout(std430, binding = 7) buffer DepthBuffer 
{
    uint depthBuffer[];
};

uniform float far;
uniform ivec2 screenResolution;

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    pixelOwnershipBuffer[coords.x + screenResolution.x * coords.y] = 0;
    depthBuffer[coords.x + screenResolution.x * coords.y] = floatBitsToUint(far);
    imageStore(depthData, coords, vec4(far));
    imageStore(outputImage, coords, vec4(1.0, 1.0, 0.0, 1.0)); 
}