#version 460

layout(local_size_x = 256) in;
layout(rgba8, binding = 0) uniform image2D outputImage;

struct Sphere 
{
    vec4 positionr;  // (x, y, z, r)
    uint index;
    int wasDrawn[3];
};

layout(std430, binding = 1) buffer SphereBuffer 
{
    Sphere spheres[];
};


layout(binding = 3, r32f) uniform image2D depthData;
layout(binding = 4) uniform sampler2D downsampledDepthTexture; 

struct FramePixelsCount
{
    uint frames;
    uint pixels;
    
};

layout(std430, binding = 5) buffer VisibilityFrameBuffer 
{
    FramePixelsCount visibilityFrameBuffer[];
};

layout(std430, binding = 6) buffer PixelOwnershipBuffer 
{
    uint pixelOwnershipBuffer[];
};

layout(std430, binding = 7) buffer DepthBuffer 
{
    uint depthBuffer[];
};

uniform mat4 view;
uniform mat4 proj;

uniform vec3 front;
uniform vec3 up;
uniform vec3 right;
uniform vec3 cameraPos;

uniform ivec2 screenResolution;
uniform float fov;

uniform int sphereCount;

const vec3 lightColor = vec3(0.01, 1.0, 0.05);
const float diffuseI = 0.9;
const int pixelsToCheck = 5;

struct bboxCorners
{
    // screen space
    vec2 minCorner;
    vec2 maxCorner;
    
};


struct ScreenRayCasting
{
    vec3 rayStart; ///< Starting caster ray in world coordinates.
    vec3 dx; ///< Per pixel delta direction vector for the x-axis.
    vec3 dy; ///< Per pixel delta direction vector for the y-axis.
};

ScreenRayCasting makeScreenRayCasting(float aspectRatio)
{
    float fovRad = radians(fov);
    float fovTan = tan(fovRad * 0.5f);
    float halfFovTan = fovTan * aspectRatio;

    // View-space ray directions for screen corners
    vec3 corner00 = normalize((-1.0f * halfFovTan) * right + (-1.0f * fovTan) * up + front); // bottom-left
    vec3 corner10 = normalize(( 1.0f * halfFovTan) * right + (-1.0f * fovTan) * up + front); // bottom-right
    vec3 corner01 = normalize((-1.0f * halfFovTan) * right + ( 1.0f * fovTan) * up + front); // top-left

    // Transform to world space only once
    vec3 wCorner00 = mat3(view) * corner00;
    vec3 wCorner10 = mat3(view) * corner10;
    vec3 wCorner01 = mat3(view) * corner01;

    // Delta per pixel
    vec3 dx = (wCorner10 - wCorner00) / float(screenResolution.x);
    vec3 dy = (wCorner01 - wCorner00) / float(screenResolution.y);

    vec3 rayStart = wCorner00;

    return ScreenRayCasting(rayStart, dx, dy);
}

uint vecToColor(vec3 lambertCos) {
    uint R = uint(lambertCos.r * 255.0);
    uint G = uint(lambertCos.g * 255.0);
    uint B = uint(lambertCos.b * 255.0);
    return (R << 0) | (G << 8) | (B << 16) | (0xFF << 24);
}

float iSphere(vec3 ro, vec3 rd, vec3 sph, float radius )
{
    vec3 oc = ro - sph;
	float b = dot( oc, rd );
	float c = dot( oc, oc ) - radius*radius;
	float h = b*b - c;
	if( h<0.0 ) return -1.0;
	return -b - sqrt( h );
}

bboxCorners getSphereBbox(const vec3 cameraSpaceSphere, const vec3 camImposPos, 
    const vec3 normCamSpaceSphere, const float sphRadius)
{
    const float sinAngle = sphRadius / (length(cameraSpaceSphere) + 1e-6f);
    const float tanAngle = tan(asin(sinAngle));
    const float quadScale = tanAngle * length(camImposPos);

    vec3 impU = normalize(cross(normCamSpaceSphere, up));
    vec3 impV = cross(impU, normCamSpaceSphere) * quadScale;
    impU *= quadScale;

    const vec3 upRightCorner = camImposPos + impU + impV;
    const vec3 upLeftCorner = camImposPos - impU + impV;
    const vec3 downRightCorner = camImposPos + impU - impV;
    const vec3 downLeftCorner = camImposPos - impU - impV;

    const vec4 upRight = proj * vec4(upRightCorner, 1.0f);
    const vec4 upLeft = proj * vec4(upLeftCorner, 1.0f);
    const vec4 downRight = proj * vec4(downRightCorner, 1.0f);
    const vec4 downLeft = proj * vec4(downLeftCorner, 1.0f);
    
    const vec3 ndcUpRight = vec3(upRight.x / upRight.w, upRight.y / upRight.w, upRight.z / upRight.w);
    const vec3 ndcUpLeft = vec3(upLeft.x / upLeft.w, upLeft.y / upLeft.w, upLeft.z / upLeft.w);
    const vec3 ndcDownRight = vec3(downRight.x / downRight.w, downRight.y / downRight.w, downRight.z / downRight.w);
    const vec3 ndcDownLeft = vec3(downLeft.x / downLeft.w, downLeft.y / downLeft.w, downLeft.z / downLeft.w);

    vec2 minCorner = min(min(ndcUpRight.xy, ndcUpLeft.xy), min(ndcDownRight.xy, ndcDownLeft.xy));
    vec2 maxCorner = max(max(ndcUpRight.xy, ndcUpLeft.xy), max(ndcDownRight.xy, ndcDownLeft.xy));


    return bboxCorners(minCorner, maxCorner); 
}

vec3 computeRd(int px, int py, 
                float fovTan, float halfFovTan)
{
    vec2 p = (-vec2(screenResolution.x, screenResolution.y) + 2.0f*vec2(px, py))/vec2(screenResolution.x, screenResolution.y);
    return normalize( p.x*right* halfFovTan + p.y*up * fovTan + front );
}

float onSphDepth(vec3 rd, int px, int py, vec3 spherePos, float r, vec3 rayStart, vec3 dx, vec3 dy)
{
    const float h = iSphere(cameraPos, rd, spherePos, r);
    const vec3 hit = (rayStart + float(px) * dx + float(py) * dy) * h;
    const float depth = (hit.z * proj[2].z + proj[3].z) / -hit.z;
    return depth;
}

bool isSphereBillboardVisible(int xcoords[pixelsToCheck], int ycoords[pixelsToCheck], float pixelDepths[pixelsToCheck])
{
    ivec2 downsampledTexSize = textureSize(downsampledDepthTexture, 0);
    const int ds_x = downsampledTexSize.x;
    const int ds_y = downsampledTexSize.y;

    float pixel1 = texelFetch(downsampledDepthTexture, ivec2(int(float(xcoords[0]*ds_x)/float(screenResolution.x)), int(float(ycoords[0]*ds_y)/float(screenResolution.y))), 0).r;
    float pixel2 = texelFetch(downsampledDepthTexture, ivec2(int(float(xcoords[1]*ds_x)/float(screenResolution.x)), int(float(ycoords[1]*ds_y)/float(screenResolution.y))), 0).r;
    float pixel3 = texelFetch(downsampledDepthTexture, ivec2(int(float(xcoords[2]*ds_x)/float(screenResolution.x)), int(float(ycoords[2]*ds_y)/float(screenResolution.y))), 0).r;
    float pixel4 = texelFetch(downsampledDepthTexture, ivec2(int(float(xcoords[3]*ds_x)/float(screenResolution.x)), int(float(ycoords[3]*ds_y)/float(screenResolution.y))), 0).r;
    float pixel5 = texelFetch(downsampledDepthTexture, ivec2(int(float(xcoords[4]*ds_x)/float(screenResolution.x)), int(float(ycoords[4]*ds_y)/float(screenResolution.y))), 0).r;

    for (int i = 0; i < pixelsToCheck; i++)
    {
        if (pixelDepths[i] <= pixel1 || 
            pixelDepths[i] <= pixel2 || 
            pixelDepths[i] <= pixel3 || 
            pixelDepths[i] <= pixel4 || 
            pixelDepths[i] <= pixel5)
            return true;
    }
    return false;
}

void drawSphere(Sphere sphere)
{
    vec3 cameraSpaceSphere = vec3(view * vec4(sphere.positionr.xyz, 1.0f));
    vec3 normCamSpaceSphere = normalize(cameraSpaceSphere);
    vec3 camImposPos = cameraSpaceSphere - normCamSpaceSphere * sphere.positionr.w;

    
    bboxCorners sphereBbox = getSphereBbox(cameraSpaceSphere, camImposPos,
        normCamSpaceSphere, sphere.positionr.w);
    
    float aspectRatio = float(screenResolution.x) / float(screenResolution.y);
    ivec2 screenMin, screenMax;

    screenMin.x = int(((sphereBbox.minCorner.x) * 0.5f + 0.5f) * float(screenResolution.x));
    screenMin.y = int((sphereBbox.minCorner.y * 0.5f + 0.5f) * float(screenResolution.y));
    screenMax.x = int(((sphereBbox.maxCorner.x) * 0.5f + 0.5f) * float(screenResolution.x));
    screenMax.y = int((sphereBbox.maxCorner.y * 0.5f + 0.5f) * float(screenResolution.y));

    const float difx = screenMax.x - screenMin.x;
    const float dify = screenMax.y - screenMin.y;

    if (difx * dify <= 2) return;

    float fovRad = radians(fov);
    float fovTan = tan(fovRad * 0.5f);
    float halfFovTan = fovTan * aspectRatio;

    ScreenRayCasting screenRayCasting = makeScreenRayCasting(aspectRatio);

    // Delta per pixel
    vec3 dx = screenRayCasting.dx;
    vec3 dy = screenRayCasting.dy;

    // Start ray origin in world
    vec3 rayStart = screenRayCasting.rayStart;


    float mid_x = min(max((screenMin.x + screenMax.x)/2, 0), screenResolution.x);
    float mid_y = min(max((screenMin.y + screenMax.y)/2, 0), screenResolution.y);

    vec3 middleLeft = computeRd(int(mid_x-difx*0.49f), int(mid_y), fovTan, halfFovTan);
    vec3 middleRight = computeRd(int(mid_x+difx*0.49f), int(mid_y), fovTan, halfFovTan);
    vec3 middleBottom = computeRd(int(mid_x), int(mid_y-dify*0.49f), fovTan, halfFovTan);
    vec3 middleTop = computeRd(int(mid_x), int(mid_y+dify*0.49f), fovTan, halfFovTan);
    vec3 middlePixelsVec = computeRd((screenMin.x + screenMax.x) / 2, (screenMin.y + screenMax.y) / 2, fovTan, halfFovTan);
    

    int xcoords[pixelsToCheck] = {int(mid_x-difx*0.49f), int(mid_x+difx*0.49f), int(mid_x), int(mid_x), (screenMin.x + screenMax.x) / 2};
    int ycoords[pixelsToCheck] = {int(mid_y), int(mid_y), int(mid_y-dify*0.49f), int(mid_y+dify*0.49f), (screenMin.y + screenMax.y) / 2};
    float pixelDepths[pixelsToCheck] = {
        onSphDepth(middleLeft, int(mid_x-difx*0.49f), int(mid_y), sphere.positionr.xyz, sphere.positionr.w, rayStart, dx, dy),
        onSphDepth(middleRight, int(mid_x+difx*0.49f), int(mid_y), sphere.positionr.xyz, sphere.positionr.w, rayStart, dx, dy),
        onSphDepth(middleBottom, int(mid_x), int(mid_y-dify*0.49f), sphere.positionr.xyz, sphere.positionr.w, rayStart, dx, dy),
        onSphDepth(middleTop, int(mid_x), int(mid_y+dify*0.49f), sphere.positionr.xyz, sphere.positionr.w, rayStart, dx, dy),
        onSphDepth(middlePixelsVec, (screenMin.x + screenMax.x) / 2, (screenMin.y + screenMax.y) / 2, sphere.positionr.xyz, sphere.positionr.w, rayStart, dx, dy),
    };
    


    if (!isSphereBillboardVisible(xcoords, ycoords, pixelDepths))
    {
        if (visibilityFrameBuffer[sphere.index].frames > 0 && 
            visibilityFrameBuffer[sphere.index].pixels == 0) 
        {
            visibilityFrameBuffer[sphere.index].frames -= 1;
        }
        else if (visibilityFrameBuffer[sphere.index].frames == 0 && 
            visibilityFrameBuffer[sphere.index].pixels == 0) 
        {
            spheres[gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_WorkGroupSize.x].wasDrawn[0] = 0;
            return;
        }
        else 
        {
            visibilityFrameBuffer[sphere.index].frames = 10;
        }
    } else
    {
        visibilityFrameBuffer[sphere.index].frames = 10;
    }
    spheres[gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_WorkGroupSize.x].wasDrawn[0] = 1;
    for (int px = max(0, screenMin.x); px < min(screenMax.x, screenResolution.x); px++)
    {
        vec3 rayColStart = rayStart + float(px) * dx;
        for (int py = max(0, screenMin.y); py < min(screenResolution.y, screenMax.y); py++)
        {

            const vec3 rd = computeRd(px, py, fovTan, halfFovTan);
            const float h = iSphere(cameraPos, rd, sphere.positionr.xyz, sphere.positionr.w);

            // imageStore(outputImage, ivec2(px, py), vec4(1.0, 1.0, 1.0, 1.0));
            // const bool showBbox = (px == screenMin.x || py == screenMin.y || px == screenMax.x - 1 || py == screenMax.y - 1);
            if (h > 0.0f) 
            {
                // imageStore(outputImage, ivec2(px, py), vec4(1.0, 0.0, 0.0, 1.0));
                const vec3 hit = (rayColStart + float(py) * dy) * h;
                const float depth = (hit.z * proj[2].z + proj[3].z) / -hit.z ;
                const uint depthUint = floatBitsToUint(depth);
                int index = px + screenResolution.x*py;
                uint old = atomicMin(depthBuffer[index], depthUint);
                if (uintBitsToFloat(old) > depth) 
                {
                    const vec3 normal = normalize( cameraPos + rd*h - sphere.positionr.xyz );
                    const float lambertCos = dot(normal, -normalize(rd*h));
                    depthBuffer[index] = depthUint;
                    pixelOwnershipBuffer[index] = sphere.index;
                    imageStore(depthData, ivec2(px, py), vec4(depth));
                    imageStore(outputImage, ivec2(px, py), vec4(lambertCos * lightColor * diffuseI, 1.0));
                }
                
            } 
        }
    }
}


void main() 
{
    uint index = gl_GlobalInvocationID.x;

    // Check if the index is out of bounds
    if (index >= sphereCount) {
        return;  // If index is greater that the amount of spheres, return
    }

    // Get sphere
    Sphere s = spheres[index];

    drawSphere(s);
    visibilityFrameBuffer[s.index].pixels = 0;
}