#version 430


layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba8, binding = 0) uniform image2D outputImage;

layout(std430, binding = 3) buffer DepthBuffer 
{
    uint depthBuffer[];
};



uniform float far;
uniform ivec2 screenResolution;

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    depthBuffer[coords.x + screenResolution.x * coords.y] = floatBitsToUint(far);
    imageStore(outputImage, coords, vec4(1.0, 1.0, 0.0, 1.0)); 
}