#version 430

layout(local_size_x = 256) in;

struct Cylinder 
{
    vec4 pa_r;  // (x, y, z, r)
    vec4 pb_r;  // (x, y, z, r)
    uint index;
    int wasDrawn[3];
};

layout(std430, binding = 9) buffer CylinderBuffer 
{
    Cylinder cylinders[];
};

struct CylinderBillboard 
{
    vec4 pa_r;   
    vec4 pb_r;   
    vec2 corner0;     
    vec2 corner1;     
    vec2 corner2;     
    vec2 corner3;     
    uint index;
    int padding1, padding2, padding3;
}; 

layout(std430, binding = 10) buffer CylinderBillboardDataBuffer
{
    CylinderBillboard cylinderBillboardData[];
};

uniform mat4 view;
uniform mat4 proj;

uniform vec3 front;
uniform vec3 up;
uniform vec3 right;
uniform vec3 cameraPos;

uniform ivec2 screenResolution;
uniform float fov;

uniform int cylinderCount;


void getCylinderBbox(out vec2 projectedPoints[4], vec3 pa, vec3 pb, vec3 center, 
    float cylRadius)
{
    // Cylinder axis
    const vec3 z = normalize(pb - pa);

    // Find orthonormal x,y axes orthogonal to cylinder axis
    vec3 x = normalize(cross(center, z));
    vec3 y = normalize(cross(x, z)); // make full basis

    // Compute impostor construction vectors.
    const float dV0 = length( pa );
    const float dV1 = length( pb );

    const float sinAngle = cylRadius / dV0;
    float		angle	 = asin( sinAngle );
    const vec3	y1		 = y * cylRadius;
    const vec3	x2		 = x * cylRadius * cos( angle );
    const vec3	y2		 = y1 * sinAngle;
    angle				 = asin( cylRadius / dV1 );
    const vec3 x3		 = x * ( dV1 - cylRadius ) * tan( angle );

    // Compute impostors vertices.
    const vec3 v1 = pa - x2 + y2;
    const vec3 v2 = pa + x2 + y2;
    const vec3 v3 = pb - x3 + y1;
    const vec3 v4 = pb + x3 + y1;

    const vec4 v1Proj = proj * vec4(v1, 1.0f);
    const vec4 v2Proj = proj * vec4(v2, 1.0f);
    const vec4 v3Proj = proj * vec4(v3, 1.0f);
    const vec4 v4Proj = proj * vec4(v4, 1.0f);

    vec3 ndcv1Proj = vec3(v1Proj.x / v1Proj.w, v1Proj.y / v1Proj.w, v1Proj.z / v1Proj.w);
    vec3 ndcv2Proj = vec3(v2Proj.x / v2Proj.w, v2Proj.y / v2Proj.w, v2Proj.z / v2Proj.w);
    vec3 ndcv3Proj = vec3(v3Proj.x / v3Proj.w, v3Proj.y / v3Proj.w, v3Proj.z / v3Proj.w);
    vec3 ndcv4Proj = vec3(v4Proj.x / v4Proj.w, v4Proj.y / v4Proj.w, v4Proj.z / v4Proj.w);

    projectedPoints[0] = vec2(ndcv1Proj);
    projectedPoints[1] = vec2(ndcv2Proj);
    projectedPoints[2] = vec2(ndcv4Proj);
    projectedPoints[3] = vec2(ndcv3Proj);
        
}

void storeCylinderBBox(Cylinder cylinder)
{
    vec3 pa = cylinder.pa_r.xyz;
    vec3 pb = cylinder.pb_r.xyz;
    float ra = cylinder.pa_r.w;
    vec3 camSpaceCylA = vec3(view * vec4(pa, 1.0f));
    vec3 camSpaceCylB = vec3(view * vec4(pb, 1.0f));

    vec3 camImpPosA, camImpPosB;
    if ( camSpaceCylA.z < camSpaceCylB.z )
	{
		camImpPosA = camSpaceCylB;
		camImpPosB = camSpaceCylA;
	}
	else
	{
		camImpPosA = camSpaceCylA;
		camImpPosB = camSpaceCylB;
	}

    vec3 center = normalize( ( camImpPosA + camImpPosB ) * 0.5f );
    vec2 projectedPoints[4];
    getCylinderBbox(projectedPoints, camImpPosA, camImpPosB, center, ra);
    
    
    for (int i = 0; i < 4; i++) 
    {
        projectedPoints[i].x = int((projectedPoints[i].x * 0.5f + 0.5f) * screenResolution.x);
        projectedPoints[i].y = int((projectedPoints[i].y * 0.5f + 0.5f) * screenResolution.y);
    }


    cylinderBillboardData[gl_GlobalInvocationID.x] =
            CylinderBillboard(cylinder.pa_r, cylinder.pb_r, 
                projectedPoints[0], projectedPoints[1], 
                projectedPoints[2], projectedPoints[3], 
                gl_GlobalInvocationID.x, 0, 0, 0);
    
}


void main() 
{
    uint index = gl_GlobalInvocationID.x;

    // Check if the index is out of bounds
    if (index >= cylinderCount) {
        return;  // If index is greater that the amount of cylinder, return
    }

    // Get cylinder bbox
    Cylinder c = cylinders[index];
    storeCylinderBBox(c);    
}