#version 430

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(rgba8, binding = 0) uniform image2D outputImage;

layout(binding = 1, r32f) uniform image2D depthData;

layout(std430, binding = 4) buffer PixelOwnershipBuffer 
{
    uint pixelOwnershipBuffer[];
};

struct CylinderBillboard 
{
    vec4 pa_r;   
    vec4 pb_r;   
    vec2 corner0;     
    vec2 corner1;     
    vec2 corner2;     
    vec2 corner3;     
    uint index;
    int padding1, padding2, padding3;
}; 

layout(std430, binding = 10) buffer CylinderBillboardDataBuffer
{
    CylinderBillboard cylinderBillboardData[];
};

layout(binding = 8) buffer CounterBuffer {
    uint cylinderCount;
};

shared CylinderBillboard sharedCylinderBillboards[1+ int(gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z)];

uniform mat4 proj;
uniform mat4 view;

uniform vec3 cameraPos;
uniform vec3 front;
uniform vec3 up;
uniform vec3 right;

uniform ivec2 screenResolution;

uniform float far;
uniform float fov;

vec3 lightColor = vec3(0.05, 1.0, 0.01);
float diffuseI = 0.9;

struct ScreenRayCasting
{
    vec3 rayStart; ///< Starting caster ray in world coordinates.
    vec3 dx; ///< Per pixel delta direction vector for the x-axis.
    vec3 dy; ///< Per pixel delta direction vector for the y-axis.
};

ScreenRayCasting makeScreenRayCasting(float aspectRatio)
{
    float fovRad = radians(fov);
    float fovTan = tan(fovRad * 0.5f);
    float halfFovTan = fovTan * aspectRatio;

    // View-space ray directions for screen corners
    vec3 corner00 = normalize((-1.0f * halfFovTan) * right + (-1.0f * fovTan) * up + front); // bottom-left
    vec3 corner10 = normalize(( 1.0f * halfFovTan) * right + (-1.0f * fovTan) * up + front); // bottom-right
    vec3 corner01 = normalize((-1.0f * halfFovTan) * right + ( 1.0f * fovTan) * up + front); // top-left

    // Transform to world space only once
    vec3 wCorner00 = mat3(view) * corner00;
    vec3 wCorner10 = mat3(view) * corner10;
    vec3 wCorner01 = mat3(view) * corner01;

    // Delta per pixel
    vec3 dx = (wCorner10 - wCorner00) / float(screenResolution.x);
    vec3 dy = (wCorner01 - wCorner00) / float(screenResolution.y);

    vec3 rayStart = wCorner00;

    return ScreenRayCasting(rayStart, dx, dy);
}

vec4 iCylinder(vec3 ro, vec3 rd, vec3 pa, vec3 pb, float ra) 
{
    vec3  ba = pb - pa;
    vec3  oc = ro - pa;

    float baba = dot(ba,ba);
    float bard = dot(ba,rd);
    float baoc = dot(ba,oc);
    
    float k2 = baba - bard*bard;
    float k1 = baba*dot(oc,rd) - baoc*bard;
    float k0 = baba*dot(oc,oc) - baoc*baoc - ra*ra*baba;
    
    
    float h = k1*k1 - k2*k0;
    if( h<0.0f ) return vec4(-1.0f);
    h = sqrt(h);
    float t = (-k1-h)/k2;

    // body
    float y = baoc + t*bard;
    if( y>0.0f && y<baba ) return vec4( t, oc+t*rd - ba*y/baba );
    
    // caps
    // t = ( ((y<0.0f) ? 0.0f : baba) - baoc)/bard;
    // if( abs(k1+k2*t)<h ) return vec4( t, ba*sign(y)/sqrt(baba) );

    return vec4(-1.0f);
}

vec3 computeRd(int px, int py, 
                float fovTan, float halfFovTan)
{
    vec2 p = (-vec2(screenResolution.x, screenResolution.y) + 2.0f*vec2(px, py))/vec2(screenResolution.x, screenResolution.y);
    return normalize( p.x*right* halfFovTan + p.y*up * fovTan + front );
}

void main()
{
    const ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    if (coords.x >= screenResolution.x || coords.y >= screenResolution.y)  return;

    const int localID = int(gl_LocalInvocationIndex);
    const int threadsPerWorkGroup = int(gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z);
    const int batches = int((int(cylinderCount)-1) / threadsPerWorkGroup) + 1;
    const int lastBatchAmount = int(cylinderCount) - (batches-1) * threadsPerWorkGroup;
    int count = threadsPerWorkGroup;

    float minDepth = imageLoad(depthData, coords).x;
    bool colorChanged = false;
    vec4 color = vec4(0.0);
    uint cylinderIndex = 0;

    float aspectRatio = float(screenResolution.x) / float(screenResolution.y);
    float fovRad = radians(fov);
    float fovTan = tan(fovRad * 0.5f);
    float halfFovTan = fovTan * aspectRatio;

    ScreenRayCasting screenRayCasting = makeScreenRayCasting(aspectRatio);

    // Delta per pixel
    vec3 dx = screenRayCasting.dx;
    vec3 dy = screenRayCasting.dy;

    // Start ray origin in world
    vec3 ray = screenRayCasting.rayStart + float(coords.x) * dx + float(coords.y) * dy;

    for (int batch = 0; batch < batches; batch++)
    {
        int batchIndex = localID + batch * threadsPerWorkGroup;
        barrier();
        if (batchIndex < int(cylinderCount))
        {
            sharedCylinderBillboards[localID] = cylinderBillboardData[batchIndex];
        }
        barrier();
        

        count = threadsPerWorkGroup;
        if (batch == batches - 1) count = min(threadsPerWorkGroup, lastBatchAmount);

        for (int index = 0; index < count; index++)
        {
            CylinderBillboard cylinderBillboard = sharedCylinderBillboards[index];
            vec2 corners[4] = vec2[](
                cylinderBillboard.corner0,
                cylinderBillboard.corner1,
                cylinderBillboard.corner2,
                cylinderBillboard.corner3
            );

            int minY = screenResolution.y;
            int maxY = 0;
            int minX = screenResolution.x;
            int maxX = 0;
            for (int i = 0; i < 4; i++) 
            {
                minY = min(minY, int(floor(corners[i].y))); 
                maxY = max(maxY, int(ceil(corners[i].y)));
                minX = min(minX, int(floor(corners[i].x))); 
                maxX = max(maxX, int(ceil(corners[i].x)));
            }

            // pixel not in the bounding box
            if ( (minX > coords.x || coords.x > maxX) || 
                (minY > coords.y || coords.y > maxY) ) 
                    continue;

            float aspectRatio = float(screenResolution.x) / float(screenResolution.y);
            float fovRad = radians(fov);
            float fovTan = tan(fovRad * 0.5f);
            float halfFovTan = fovTan * aspectRatio;

            ScreenRayCasting screenRayCasting = makeScreenRayCasting(aspectRatio);

            // Delta per pixel
            vec3 dx = screenRayCasting.dx;
            vec3 dy = screenRayCasting.dy;

            // Start ray origin in world
            vec3 rayStart = screenRayCasting.rayStart;

            vec3 ray = rayStart + float(coords.y) * dy + float(coords.x) * dx;

            const vec3 rd = computeRd(coords.x, coords.y, fovTan, halfFovTan);
            vec4 tnor = iCylinder( cameraPos, rd, cylinderBillboard.pa_r.xyz, cylinderBillboard.pb_r.xyz, cylinderBillboard.pa_r.w);

            // imageStore(outputImage, coords, vec4(0.0));
            if (tnor.x > 0.0f) 
            {
                const vec3 hit = ray * tnor.x;
                const float depth = (hit.z * proj[2].z + proj[3].z) / -hit.z ;
                if (minDepth > depth) 
                {
                    const vec3 normal = normalize(vec3(tnor.y, tnor.z, tnor.w));
                    const float lambertCos = dot(normal, -normalize(rd*tnor.x));
                    minDepth = depth;
                    color = vec4(lambertCos * lightColor * diffuseI, 1.0);
                    cylinderIndex = cylinderBillboard.index;
                    if (!colorChanged) colorChanged = true;
                }
                
            }
                
        }
        
    }
    if (colorChanged) 
    {
        pixelOwnershipBuffer[coords.x + screenResolution.x*coords.y] = cylinderIndex; 
        imageStore(outputImage, coords, color);
        imageStore(depthData, coords, vec4(minDepth));
    }
    // else imageStore(outputImage, coords, vec4(1.0, 0.0, 0.0, 1.0));
}