#version 430

layout(local_size_x = 256) in;

struct CylinderIndex
{
    uint sphereIndexA;
    uint sphereIndexB;
    float radius;
    uint _padding;
};

layout(std430, binding = 6) buffer SphereBuffer
{
    vec4 spheres[];
};

layout(std430, binding = 9) buffer CylinderBuffer 
{
    CylinderIndex cylinderIndices[];
};

struct CylinderBillboard 
{
    vec4 pa_r;   
    vec4 pb_r;   
    vec2 corner0;     
    vec2 corner1;     
    vec2 corner2;     
    vec2 corner3;     
    uint index;
    int padding1, padding2, padding3;
}; 

layout(std430, binding = 10) buffer CylinderBillboardDataBuffer
{
    CylinderBillboard cylinderBillboardData[];
};

layout(binding = 8) buffer CounterBuffer {
    uint counter;
};

uniform mat4 view;
uniform mat4 proj;

uniform vec4 frustumTopFace;
uniform vec4 frustumBottomFace;
uniform vec4 frustumRightFace;
uniform vec4 frustumLeftFace;
uniform vec4 frustumFarFace;
uniform vec4 frustumNearFace;

uniform vec3 front;
uniform vec3 up;
uniform vec3 right;
uniform vec3 cameraPos;

uniform ivec2 screenResolution;
uniform float fov;

uniform int cylinderCount;

// frustum culling
struct BBox3D
{
    vec3 mMin;
    vec3 mMax;
};

bool isOnOrForwardPlaneAABB(vec4 plane, BBox3D bbox) 
{
    vec3 negativeVertex = bbox.mMin;
    vec3 normal = plane.xyz;
    float distance = plane.w;

    if (normal.x >= 0) negativeVertex.x = bbox.mMax.x;
        else negativeVertex.x = bbox.mMin.x;

    if (normal.y >= 0) negativeVertex.y = bbox.mMax.y;
        else negativeVertex.y = bbox.mMin.y;

    if (normal.z >= 0) negativeVertex.z = bbox.mMax.z;
        else negativeVertex.z = bbox.mMin.z;

    return dot(normal, negativeVertex) - distance >= 0;
}

bool isCylinderInside(vec3 pa, vec3 pb, float radius)
{
    vec3 a = pb - pa;
    vec3 e = radius*sqrt( 1.0f - a*a/dot(a,a) );
    BBox3D bbox3d = BBox3D(min( pa - e, pb - e ), max( pa + e, pb + e ));

    return isOnOrForwardPlaneAABB(frustumLeftFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumRightFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumFarFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumNearFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumTopFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumBottomFace, bbox3d);
}
// frustum culling

void getCylinderBbox(out vec2 projectedPoints[4], vec3 pa, vec3 pb, vec3 center, 
    float cylRadius)
{
    // Cylinder axis
    const vec3 z = normalize(pb - pa);

    // Find orthonormal x,y axes orthogonal to cylinder axis
    vec3 x = normalize(cross(center, z));
    vec3 y = normalize(cross(x, z)); // make full basis

    // Compute impostor construction vectors.
    const float dV0 = length( pa );
    const float dV1 = length( pb );

    const float sinAngle = cylRadius / dV0;
    float		angle	 = asin( sinAngle );
    const vec3	y1		 = y * cylRadius;
    const vec3	x2		 = x * cylRadius * cos( angle );
    const vec3	y2		 = y1 * sinAngle;
    angle				 = asin( cylRadius / dV1 );
    const vec3 x3		 = x * ( dV1 - cylRadius ) * tan( angle );

    // Compute impostors vertices.
    const vec3 v1 = pa - x2 + y2;
    const vec3 v2 = pa + x2 + y2;
    const vec3 v3 = pb - x3 + y1;
    const vec3 v4 = pb + x3 + y1;

    const vec4 v1Proj = proj * vec4(v1, 1.0f);
    const vec4 v2Proj = proj * vec4(v2, 1.0f);
    const vec4 v3Proj = proj * vec4(v3, 1.0f);
    const vec4 v4Proj = proj * vec4(v4, 1.0f);

    vec3 ndcv1Proj = vec3(v1Proj.x / v1Proj.w, v1Proj.y / v1Proj.w, v1Proj.z / v1Proj.w);
    vec3 ndcv2Proj = vec3(v2Proj.x / v2Proj.w, v2Proj.y / v2Proj.w, v2Proj.z / v2Proj.w);
    vec3 ndcv3Proj = vec3(v3Proj.x / v3Proj.w, v3Proj.y / v3Proj.w, v3Proj.z / v3Proj.w);
    vec3 ndcv4Proj = vec3(v4Proj.x / v4Proj.w, v4Proj.y / v4Proj.w, v4Proj.z / v4Proj.w);

    projectedPoints[0] = vec2(ndcv1Proj);
    projectedPoints[1] = vec2(ndcv2Proj);
    projectedPoints[2] = vec2(ndcv4Proj);
    projectedPoints[3] = vec2(ndcv3Proj);
        
}



void storeCylinderBBox(vec3 pa, vec3 pb, float ra, uint cylinderIndex)
{
    vec3 camSpaceCylA = vec3(view * vec4(pa, 1.0f));
    vec3 camSpaceCylB = vec3(view * vec4(pb, 1.0f));

    vec3 camImpPosA, camImpPosB;
    if ( camSpaceCylA.z < camSpaceCylB.z )
	{
		camImpPosA = camSpaceCylB;
		camImpPosB = camSpaceCylA;
	}
	else
	{
		camImpPosA = camSpaceCylA;
		camImpPosB = camSpaceCylB;
	}

    vec3 center = normalize( ( camImpPosA + camImpPosB ) * 0.5f );
    vec2 projectedPoints[4];
    getCylinderBbox(projectedPoints, camImpPosA, camImpPosB, center, ra);
        
    for (int i = 0; i < 4; i++) 
    {
        projectedPoints[i].x = int((projectedPoints[i].x * 0.5f + 0.5f) * screenResolution.x);
        projectedPoints[i].y = int((projectedPoints[i].y * 0.5f + 0.5f) * screenResolution.y);
    }

    uint currentCounter = atomicAdd(counter, 1);
    cylinderBillboardData[int(currentCounter)] =
        CylinderBillboard(vec4(pa, ra), vec4(pb, ra), 
            projectedPoints[0], projectedPoints[1], 
            projectedPoints[2], projectedPoints[3], 
            currentCounter, 0, 0, 0);
}


void main() 
{
    uint index = gl_GlobalInvocationID.x;

    // Check if the index is out of bounds
    if (index >= cylinderCount) {
        return;  // If index is greater that the amount of cylinder, return
    }

    // Get cylinder bbox
    CylinderIndex c = cylinderIndices[index];
    vec3 pa = spheres[c.sphereIndexA].xyz;
    vec3 pb = spheres[c.sphereIndexB].xyz;
    float ra = c.radius;

    if (isCylinderInside(pa, pb, ra)) 
        storeCylinderBBox(pa, pb, ra, index);
    
}