#version 460

layout(local_size_x = 256) in;

struct CylinderIndex
{
    uint sphereIndexA;
    uint sphereIndexB;
    float radius;
    uint _padding;
};

layout(std430, binding = 6) buffer SphereBuffer
{
    vec4 spheres[];
};

layout(std430, binding = 4) buffer CylinderBuffer 
{
    CylinderIndex cylinderIndices[];
};

layout(std430, binding = 5) buffer VisibleCylinderIndexes 
{
    uint visibilityIndex[];
};

layout(binding = 3) buffer FrustumCounterBuffer {
    uint frustCullcounter;
};

uniform vec4 frustumTopFace;
uniform vec4 frustumBottomFace;
uniform vec4 frustumRightFace;
uniform vec4 frustumLeftFace;
uniform vec4 frustumFarFace;
uniform vec4 frustumNearFace;

uniform int cylinderCount;

// frustum culling
struct BBox3D
{
    vec3 mMin;
    vec3 mMax;
};

bool isOnOrForwardPlaneAABB(vec4 plane, BBox3D bbox) 
{
    vec3 negativeVertex = bbox.mMin;
    vec3 normal = plane.xyz;
    float distance = plane.w;

    if (normal.x >= 0) negativeVertex.x = bbox.mMax.x;
        else negativeVertex.x = bbox.mMin.x;

    if (normal.y >= 0) negativeVertex.y = bbox.mMax.y;
        else negativeVertex.y = bbox.mMin.y;

    if (normal.z >= 0) negativeVertex.z = bbox.mMax.z;
        else negativeVertex.z = bbox.mMin.z;

    return dot(normal, negativeVertex) - distance >= 0;
}

bool isCylinderInside(vec3 pa, vec3 pb, float radius)
{
    vec3 a = pb - pa;
    vec3 e = radius*sqrt( 1.0f - a*a/dot(a,a) );
    BBox3D bbox3d = BBox3D(min( pa - e, pb - e ), max( pa + e, pb + e ));

    return isOnOrForwardPlaneAABB(frustumLeftFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumRightFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumFarFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumNearFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumTopFace, bbox3d) &&
           isOnOrForwardPlaneAABB(frustumBottomFace, bbox3d);
}
// frustum culling


void main()
{
    uint index = gl_GlobalInvocationID.x;

    // Check if the index is out of bounds
    if (index >= cylinderCount) {
        return;  // If index is greater that the amount of cylinders, return
    }

    // Get cylinder
    CylinderIndex c = cylinderIndices[index];
    vec3 pa = spheres[c.sphereIndexA].xyz;
    vec3 pb = spheres[c.sphereIndexB].xyz;
    float ra = c.radius;

    if (isCylinderInside(pa, pb, ra))
    {
        uint oldIndex = atomicAdd(frustCullcounter, 1);
        visibilityIndex[oldIndex] = index;
    } 
}